biglotteryfund/grants-service

.eslintrc.js
grants/__snapshots__/search.test.js.snap
grants/search.js
grants/search.test.js

I was looking to improve the text search by requiring results to have a minimum weight:
```
{ $match: { _textScore: { $gt: 1.0 } } }
```
Noticed that our current approach for getting totals, results, and facets means that not all queries are supported across all three so the total results counts can end up wrong.
Reading the docs a bit more it turns out that the whole point of `$facet` is that it lets you perform a single pipeline query for everything you need.
The only caveat to note is that because `$facet` returns everything in arrays we need to do a little massaging work at the end to keep the same json response as before.

Refactor to use a single pipeline

---

scripts/clean-grant-data

Our `plannedDates` field was a bit wrong, it was pushing the start and end dates into separate array items, they should be part of the same event object.

Add startDate and endDate to a single array

---

grants/__snapshots__/search.test.js.snap
grants/search.js
grants/search.test.js

This change (credit to @davidrapson) wraps search words in quotes to ensure each term appears in the search result. This change means much fewer results for queries, eg:
(but hopefully more accurate results!)
This also allows for negation, eg. if a term is prefixed with `-` then it isn't wrapped (which breaks the negation):

Improve querying

---

grants/index.js
grants/search.js
grants/search.test.js
package.json

Lambda functions send all logs to a cloudwatch logs stream by default. Testing this to see what this looks like. Note: I'm temporarily breaking postcode lookups in order to check error handling.

Test cloudwatch logs

---

grants/__snapshots__/search.test.js.snap
grants/search.js

Adds some new facets (or tweaks existing ones) to aid with https://github.com/biglotteryfund/blf-alpha/pull/1336
- We now have a country facet:
- Amount awarded now generates its strings / query parameters on the API side:
This will make UI rendering easier (and in the case of countries, dynamic, like the other facet filters)

Enhance facets

---

README.md
lib/mongo.js
scripts/clean-grant-data
scripts/create-indices
scripts/export-local
scripts/import-csv
scripts/import-remote

Added some steps here to make it easier to export a local database to a custom collection name and then output it to a different collection name, too.
Convention I'm going with for exporting to production db = `grants-2018-10-11`.

Improve import scripts

---

grants/search.js

Excludes words like "project" if possible to avoid DB strain.
Also dynamically calculates whether `3/6 month ago` date ranges should be shown.

Exclude common words from queries

---

grants/index.js
grants/search.js
translations.js

Adds a bunch of translations to facets / sort options. Also tweaks the cached facets endpoint to fetch facets in both locales and store them as a single object, then retrieves the relevant one when fetching them later.

Translate facets

---

grants/index.js
grants/search.js

Forgot that the facets now need to be passed the query results so we can determine whether we should show the 3/6 month options. For cached facets we now pass the most recent grant, which determines whether we show these options. Also reversed them so they display properly (eg. 3 then 6 months)

Make sure we include recent award dates for cached facets

---

data/fundingProgrammes.js
grants/search.js
scripts/clean-grant-data

Allows us to distinguish between Awards For All and its regions, and fixes this inconsistency:

Reference funding programmes by code

---

lib/indices.js

I think these just represent different combos of filters, but Mongo suggested adding them.

Add suggested indices from Mongo Cloud

---

grants/index.js
grants/search.js
lib/indices.js
scripts/clean-grant-data

For performance reasons, this flattens single-element arrays into flat objects. This is mainly so we can add mongo indices that otherwise aren't allowed, and the only reason we were doing this was to strictly follow the GrantNav format. 
Although the data is now stored as objects, not arrays, the API returns them as single-element arrays as before, in order to be compatible with the frontend (which still expects arrays). Once we verify this is more performant, we can remove this behaviour and switch the frontend to use the objects.

Remove arrays from data

---

README.md
grants/index.js
grants/search.js
grants/search.test.js
lib/indices.js
translations.js

Noticed that the main remaining thing that googlebot is working its way through is the location links from grant pages. This PR optimises that query.
This is a fairly specific change though so we may want to revisit this. Adds a $project step if the query is only a location query to encourage it to use a better index. Seems backed up by this https://jira.mongodb.org/browse/SERVER-7568?focusedCommentId=814169&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-814169
Feels a bit too magic to me but I've confirmed that it makes a noticable difference.

Improve index for location queries

---

package.json

Locks event stream version. Our lock file was already on `3.3.4` but the range in package.json theoretically allows this to be updated if we ran an install. Explicitly locking to `3.3.4`.
You can run `npm ls event-stream flatmap-stream` to confirm that flatmap-stream should not be listed.

Lock event-stream version to 3.3.4

---

scripts/clean-grant-data

Mark Waterhouse pointed out this error:
This change renames the second one to match the first – I couldn't think of a reliable way of automating this and I checked the entire list to see if this has happened in any other cases (it hasn't), so a manual rename seemed simplest.
It also silences a `moment` parser warning as I realised we can specify multiple date formats to attempt to parse a string with, rather than just one.
Once this is approved I can "deploy" the new data, which will merge those duplicate programmes.

Data cleanup

---

data/fundingProgrammes.js

This renames all of the links for funding programmes to the new, archived pages, rather than the legacy pages. Pairs with https://github.com/biglotteryfund/blf-alpha/pull/1600

Use the new slugs for all the migrated legacy funding programmes

---

package.json
scripts/verify-data
test/compare-facets.test.js

This approach is a bit unusual so curious on your thoughts @davidrapson.
Basically, the point here is to test that newly-imported grant data doesn't introduce unexpected things (eg. in January we inadvertently broke the local authority search by incorrectly parsing new data and adding a bunch of new locations which weren't LAs).
It does this by requesting the currently-live facets, generating new facets based on the new data, and running some comparison tests against the two.
The test script would need to be run during the import process (eg. at the end) as a kind of smoke test – it doesn't really fit into the regular test paradigm as it's a kind of a one-off that's tied to the (manual) import task.
Thoughts/ideas welcome!

[WIP] Add tests for import process

---

scripts/clean-grant-data

This comes via the Data team – the easiest/most reliable way to clear out embargoed items is to just remove the ones with a generic/missing description.

Clean out anything without a press summary (eg. embargoed)

---

.travis.yml

Lambda is already using Node 10, but travis was out of sync.
Upgrading this allows other dev dependencies to be upgraded as many are now dropping node 8 support since it is EOL.

Upgrade travis node version to 10.x

---

grants/search.js
lib/indices.js
scripts/clean-grant-data
scripts/verify-data

Fixed https://github.com/biglotteryfund/blf-alpha/issues/3527 – the new GMS data drops the concept of sub-types for organisations, so this change removes it and makes the filter/facet a single-level rather than nested, eg:
This matches the format from GMS going forward.

Clean up organisation type field

---

data/fundingProgrammes.js
scripts/clean-grant-data

Addition of new funding programme according to new grant import, slug matches from cms (be sure to double check).
Included small fix when a description is not added in an import, clear error message rather than a bulk error.

New funding programme + fix

---

serverless.yml

The files have reached lambdas hard limit and cannot be deployed to. To reduce the file size, we exclude the data folder from the serverless.yml

exclude data folder from yml to reduce size

---

serverless.yml

This was previously set by default to true, but appears to be setting to false by default due to the increased file size.

manually set excludedevdependencies to reduce file size
