biglotteryfund/grants-service

grants/index.js
grants/search.js
lib/mongo.js

- Add endpoint for single entries
- Add additional filters for amounts
- Update pipelines to avoid extra processing for facets

Add endpoint for single entries and add additional filters

---

grants/search.js

Quick pattern match in case someone enters (just) a postcode.
Could probably expand this to find a postcode inside another string and strip it out, but for now let's keep it simple (stupid).

Detect postcode searches

---

lib/indices.js

Add recommended indexes from performance advisor. I've added these already through Compass, including them in the script for reference / future runs.

Add recommended indexes from performance advisor

---

grants/__snapshots__/search.test.js.snap
grants/search.js

Adds pagination hints and a `localAuthority` filter.

Add metadata

---

grants/error.js
grants/errors.js
grants/index.js
grants/search.js
lib/mongo.js

Adds some error handling so we can distinguish between problems on the frontend.

Normalise errors

---

scripts/clean-grant-data
scripts/create-indices

This updates the import script to cleanup some dodgy data, eg. this sort of thing:

Data cleanup

---

.gitignore
scripts/clean-grant-data
serverless.yml

Removes location fields for records without them.

Clean missing locations

---

grants/search.js

Return consistent label/value for facets

Return consistent label/value for facets

---

grants/__snapshots__/search.test.js.snap
grants/index.js
grants/search.js
grants/search.test.js
lib/indices.js
lib/mongo.js
package-lock.json
package.json
scripts/create-indices

- Use server-timings in place of custom timing
- Bump dependencies
- Remove usingFacetCache, can tell by _id returned in facets object

Add server-timings and upgrade dependencies

---

grants/__snapshots__/search.test.js.snap
grants/search.js

Return sort options as part of meta

---

grants/search.js
translations.js

This is just a basic dictionary for now – will be added to when we get the full translations. This is just concerned with the facets for now. Would be good to get a first-pass review even before we have the translations (this'll work without them).

Add basic translation function

---

data/fundingProgrammes.js
grants/search.js
scripts/clean-grant-data
scripts/import-all.sh
scripts/import-csv

Discovered a few issues when importing new data so this attempts to fix them.

Quick fixes

---

grants/search.js

Convert last 3/6 months to date presets (`last3Months` or `last6Months`).
Fixes bug where the date ranges for last 3/6 months get out of sync due to the pre built facets from `build-facets`, breaking the selected state and causing mismatch in date ranges. Using presets avoids this as the keys are static.

Convert last 3/6 months to date presets

---

grants/index.js
grants/search.js

Adds custom endpoint for recipient with a much simpler query and as a result uses a more efficient index. Bit of duplication going on but should be good for now.

Add recipient endpoint

---

README.md
package-lock.json
scripts/clean-grant-data

Tweaks the data import logic to remove a couple of specific grants which shouldn't be there. Longer term we need a better fix for this, but for now it's workable.

Remove some invalid grants from the import

---

.eslintrc.js
grants/search.js
lib/geocodes.js
package-lock.json
package.json
scripts/clean-grant-data
scripts/export-years
scripts/modules/dataTweaks.js
scripts/modules/helpers.js

A bit of a mixed bag in here so will comment through the code instead.
Main changes are: the newest data export (eg. 2019 data) contained quite a few format changes compared to the previous datasets. Shamefully I didn't notice this at import time. 
A result of this is that all the records in that dataset (a few hundred) didn't have proper `organisationType` fields, and that incorrectly-parsed location codes meant that we claimed to offer over 600 local authorities to choose from (there are only 418).
These changes attempt to parse the differing formats more intelligently and I've tested it diligently to ensure that we didn't break any legacy data while fixing the old ones.

Fix data inconsistencies

---

grants/index.js
grants/search.js
grants/search.test.js
lib/check-spelling.js
lib/check-spelling.test.js
lib/indices.js
lib/mongo.js
package-lock.json
package.json
translations.js

We currently handle spellchecking in the main app but it probably makes more sense to live here.

Add searchSuggestions to meta response

---

.prettierignore
.travis.yml
data/fundingProgrammes.js
grants/errors.js
grants/index.js
grants/search.js
grants/search.test.js
lib/check-spelling.js
lib/check-spelling.test.js
lib/geocodes.js
lib/indices.js
lib/mongo.js
lib/strings.js
lib/strings.test.js
package-lock.json
package.json
scripts/modules/dataTweaks.js
scripts/modules/helpers.js
test/compare-facets.test.js
test/fixtures/grants.js
test/mongo-environment.js
test/setup.js
test/teardown.js
translations.js

Upgrade prettier to v2 and reformat all files.

Upgrade prettier to v2

---

package.json

start-test command added which doesnt use nodemon

---

data/fundingProgrammes.js

New programme added for grants upload

Added new programme

---

data/fundingProgrammes.js

updated programmes

---

serverless.yml

exclude node modules folder from yml to reduce size

exclude node modules folder from yml to reduce size

---

serverless.yml

exclude unused node modules as opposed to all

exclude unused node modules as opposed to all

---

serverless.yml

include modules required, exclude rest

include modules required, exclude rest

---

data/fundingProgrammes.js

Updated to match programmes of codes.

updated url paths
